title: 'Dev Tools'
author: 'Reinaldo de Padua'
description: 'Really cool blog about ... something'
permalink: /:title/
lang: 'pt-br'

show_footer: true # show the "previous" and "next" links at the end of each post
dark_theme: true # use the dark mode as default
dark_header: true # keep the header dark
dark_footer: true # keep the footer dark
style: minimal # use a simpler style inspired by the minima theme

navigation: # site navigation in the header
  - TOOLS.md
  - README.md
  - Github: 'https://github.com/ReinaldoPadua'

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
#  rss: "/contrast/feed.xml"

comments: true # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
  - jekyll-feed
  - jekyll-default-layout
